name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: unit test
        run: npm test
      - name: e2e test
        run: npm run test:e2e
      - name: lint code
        run: npm lint

  db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Installing postgresql
        uses: postgres/setup-postgresql@v1
        with:
          version: 14.2
      - name: Creating database
        run: psql -U postgres -c "CREATE DATABASE cloth_store;"
